{
  "openapi": "3.0.0",
  "info": {
    "title": "Développement et Service Cloud API",
    "version": "v1"
  },
  "servers": [],
  "paths": {
    "/api/movies/": {
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array"
                }
              }
            }
          },
          "500": {
            "description": "Une erreur est survenue lors de la récupération des films",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Une erreur est survenue lors de la récupération des films",
                  "type": "string"
                }
              }
            }
          }
        },
        "description": "Retourne les films en BDD",
        "operationId": "GET_api-movies"
      }
    },
    "/api/movies/{idMovie}": {
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "_id": "573a1390f29313caabcd42e8",
                    "plot": "A group of bandits stage a brazen train hold-up, only to find a determined posse hot on their heels.",
                    "genres": [
                      "Short",
                      "Western"
                    ],
                    "runtime": 11,
                    "cast": [
                      "A.C. Abadie",
                      "Gilbert M. 'Broncho Billy' Anderson",
                      "George Barnes",
                      "Justus D. Barnes"
                    ],
                    "poster": "https://m.media-amazon.com/images/M/MV5BMTU3NjE5NzYtYTYyNS00MDVmLWIwYjgtMmYwYWIxZDYyNzU2XkEyXkFqcGdeQXVyNzQzNzQxNzI@._V1_SY1000_SX677_AL_.jpg",
                    "title": "The Great Train Robbery",
                    "fullplot": "Among the earliest existing films in American cinema - notable as the first film that presented a narrative story to tell - it depicts a group of cowboy outlaws who hold up a train and rob the passengers. They are then pursued by a Sheriff's posse. Several scenes have color included - all hand tinted.",
                    "languages": [
                      "English"
                    ],
                    "released": "1903-12-01T00:00:00.000Z",
                    "directors": [
                      "Edwin S. Porter"
                    ],
                    "rated": "TV-G",
                    "awards": {
                      "wins": 1,
                      "nominations": 0,
                      "text": "1 win."
                    },
                    "lastupdated": "2015-08-13 00:27:59.177000000",
                    "year": 1903,
                    "imdb": {
                      "rating": 7.4,
                      "votes": 9847,
                      "id": 439
                    },
                    "countries": [
                      "USA"
                    ],
                    "type": "movie",
                    "tomatoes": {
                      "viewer": {
                        "rating": 3.7,
                        "numReviews": 2559,
                        "meter": 75
                      },
                      "fresh": 6,
                      "critic": {
                        "rating": 7.6,
                        "numReviews": 6,
                        "meter": 100
                      },
                      "rotten": 0,
                      "lastUpdated": "2015-08-08T19:16:10.000Z"
                    },
                    "num_mflix_comments": 3
                  },
                  "type": "object"
                }
              }
            }
          },
          "404": {
            "description": "Film non trouvé",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Film non trouvé",
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Une erreur est survenue",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Une erreur est survenue",
                  "type": "string"
                }
              }
            }
          }
        },
        "description": "Retourne un film",
        "operationId": "GET_api-movies-idMovie"
      },
      "post": {
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "acknowledged": true,
                    "insertedId": "66008551b6dba8cfa1ba394f"
                  },
                  "type": "object"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "_original": {
                      "plot": "Test",
                      "genres": [
                        "TEst"
                      ],
                      "runtime": "Test",
                      "poster": "Test",
                      "title": "My title"
                    },
                    "details": [
                      {
                        "message": "\"lastupdated\" is required",
                        "path": [
                          "lastupdated"
                        ],
                        "type": "any.required",
                        "context": {
                          "label": "lastupdated",
                          "key": "lastupdated"
                        }
                      }
                    ]
                  },
                  "type": "object"
                }
              }
            }
          },
          "500": {
            "description": "Une erreur est survenue lors de la création du film",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Une erreur est survenue lors de la création du film",
                  "type": "string"
                }
              }
            }
          }
        },
        "description": "Création d'un film",
        "operationId": "POST_api-movies-idMovie",
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
                "plot": "Test",
                "genres": [
                  "TEst"
                ],
                "runtime": "Test",
                "poster": "Test",
                "title": "My title",
                "lastupdated": "2024-03-24T21:45:45.920Z"
              },
              "schema": {
                "type": "object"
              }
            }
          },
          "required": true
        }
      },
      "put": {
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "example": "{\n  \"lastErrorObject\": {\n    \"n\": 1,\n    \"updatedExisting\": true\n  },\n  \"value\": {\n    \"_id\": \"66008c60b54215b69f20f875\",\n    \"plot\": \"Test\",\n    \"genres\": [\n      \"TEst\"\n    ],\n    \"runtime\": \"Test\",\n    \"poster\": \"Test\",\n    \"title\": \"My title\",\n    \"lastupdated\": 1711311968951,\n    \"num_mflix_comments\": 0\n  },\n  \"ok\": 1,\n  \"$clusterTime\": {\n    \"clusterTime\": {\n      \"$timestamp\": \"7350030189943848974\"\n    },\n    \"signature\": {\n      \"hash\": \"2l1aBildKSuLmZ4RX2vUtaovQvU=\",\n      \"keyId\": {\n        \"low\": 2,\n        \"high\": 1698416132,\n        \"unsigned\": false\n      }\n    }\n  },\n  \"operationTime\": {\n    \"$timestamp\": \"7350030189943848974\"\n  }\n",
                  "type": "object"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "_original": {
                      "plot": "Test",
                      "genres": [
                        "TEst"
                      ],
                      "runtime": "Test",
                      "poster": "Test",
                      "title": "My title"
                    },
                    "details": [
                      {
                        "message": "\"lastupdated\" is required",
                        "path": [
                          "lastupdated"
                        ],
                        "type": "any.required",
                        "context": {
                          "label": "lastupdated",
                          "key": "lastupdated"
                        }
                      }
                    ]
                  },
                  "type": "object"
                }
              }
            }
          },
          "404": {
            "description": "Film non trouvé",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Film non trouvé",
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Une erreur est survenue lors de la MAJ du film",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Une erreur est survenue lors de la MAJ du film",
                  "type": "string"
                }
              }
            }
          }
        },
        "description": "Modification d'un film",
        "operationId": "PUT_api-movies-idMovie",
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
                "_id": "XXXXXX",
                "plot": "Test",
                "genres": [
                  "TEst"
                ],
                "runtime": "Test",
                "poster": "Test",
                "title": "My title 2",
                "lastupdated": "2024-03-24T21:45:45.920Z",
                "num_mflix_comments": 0
              },
              "schema": {
                "type": "object"
              }
            }
          },
          "required": true
        }
      },
      "delete": {
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "acknowledged": true,
                    "deletedCount": 1
                  },
                  "type": "object"
                }
              }
            }
          },
          "404": {
            "description": "Film non trouvé",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Film non trouvé",
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Une erreur est survenue lors de la suppression du film",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Une erreur est survenue lors de la suppression du film",
                  "type": "string"
                }
              }
            }
          }
        },
        "description": "Suppression d'un film",
        "operationId": "DELETE_api-movies-idMovie"
      },
      "parameters": [
        {
          "name": "idMovie",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ]
    },
    "/api/movies/{idMovie}/comments": {
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "example": [
                    {
                      "_id": "66006e605e3ea8d6de368a45",
                      "name": "Test",
                      "email": "test@test.new",
                      "movie_id": "573a1390f29313caabcd42e8",
                      "text": "Test Text",
                      "date": "2024-03-24T19:45:45.920Z"
                    },
                    {
                      "_id": "6600709184e254f6a25447f7",
                      "name": "Test",
                      "email": "test@test.com",
                      "movie_id": "573a1390f29313caabcd42e8",
                      "text": "Test Text",
                      "date": "2024-03-24T18:45:45.920Z"
                    },
                    {
                      "_id": "660081d05b9fb30b5eb53222",
                      "name": "Test",
                      "email": "test@test.com",
                      "movie_id": "573a1390f29313caabcd42e8",
                      "text": "Test Text",
                      "date": "2024-03-24T21:45:45.920Z"
                    }
                  ],
                  "type": "array"
                }
              }
            }
          },
          "404": {
            "description": "Film non trouvé",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Film non trouvé",
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Erreur",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Erreur",
                  "type": "string"
                }
              }
            }
          }
        },
        "description": "Retourne les commentaires d'un film",
        "operationId": "GET_api-movies-idMovie-comments"
      },
      "parameters": [
        {
          "name": "idMovie",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ]
    },
    "/api/movies/{idMovie}/comments/{idComment}": {
      "get": {
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "example": [
                    {
                      "_id": "5a9427648b0beebeb69579e7",
                      "name": "Mercedes Tyler",
                      "email": "mercedes_tyler@fakegmail.com",
                      "movie_id": "573a1390f29313caabcd4323",
                      "text": "Eius veritatis vero facilis quaerat fuga temporibus. Praesentium expedita sequi repellat id. Corporis minima enim ex. Provident fugit nisi dignissimos nulla nam ipsum aliquam.",
                      "date": "2002-08-18T04:56:07.000Z"
                    }
                  ],
                  "type": "array"
                }
              }
            }
          },
          "404": {
            "description": "Commentaire non trouvé",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Commentaire non trouvé",
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Une erreur est survenue",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Une erreur est survenue",
                  "type": "string"
                }
              }
            }
          }
        },
        "description": "Retourne un commentaire",
        "operationId": "GET_api-movies-idMovie-comments-idComment"
      },
      "post": {
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "acknowledged": true,
                    "insertedId": "66008fe4b54215b69f20f876"
                  },
                  "type": "object"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "_original": {
                      "email": "test@test.com",
                      "movie_id": "573a1390f29313caabcd42e8",
                      "text": "Test Text",
                      "date": "2024-03-24T21:45:45.920Z"
                    },
                    "details": [
                      {
                        "message": "\"name\" is required",
                        "path": [
                          "name"
                        ],
                        "type": "any.required",
                        "context": {
                          "label": "name",
                          "key": "name"
                        }
                      }
                    ]
                  },
                  "type": "object"
                }
              }
            }
          },
          "500": {
            "description": "Une erreur est survenue lors de la création du commentaire",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Une erreur est survenue lors de la création du commentaire",
                  "type": "string"
                }
              }
            }
          }
        },
        "description": "Création d'un commentaire",
        "operationId": "POST_api-movies-idMovie-comments-idComment",
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
                "name": "Test",
                "email": "test@test.com",
                "movie_id": "573a1390f29313caabcd42e8",
                "text": "Test Text",
                "date": "2024-03-24T21:45:45.920Z"
              },
              "schema": {
                "type": "object"
              }
            }
          },
          "required": true
        }
      },
      "put": {
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "lastErrorObject": {
                      "n": 1,
                      "updatedExisting": true
                    },
                    "value": {
                      "_id": "66006e605e3ea8d6de368a45",
                      "name": "Test",
                      "email": "test@test.new",
                      "movie_id": "573a1390f29313caabcd42e8",
                      "text": "Test Text",
                      "date": "2024-03-24T19:45:45.920Z"
                    },
                    "ok": 1,
                    "$clusterTime": {
                      "clusterTime": {
                        "$timestamp": "7350033445529059338"
                      },
                      "signature": {
                        "hash": "cWRzNGKFSnDa9qBFa6/R1KA1cC8=",
                        "keyId": {
                          "low": 2,
                          "high": 1698416132,
                          "unsigned": false
                        }
                      }
                    },
                    "operationTime": {
                      "$timestamp": "7350033445529059338"
                    }
                  },
                  "type": "object"
                }
              }
            }
          },
          "400": {
            "description": "Bad Request",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "_original": {
                      "_id": "66006e605e3ea8d6de368a45",
                      "name": "Test",
                      "email": "test@test.new",
                      "movie_id": "573a1390f29313caabcd42e8",
                      "text": "Test Text"
                    },
                    "details": [
                      {
                        "message": "\"date\" is required",
                        "path": [
                          "date"
                        ],
                        "type": "any.required",
                        "context": {
                          "label": "date",
                          "key": "date"
                        }
                      }
                    ]
                  },
                  "type": "object"
                }
              }
            }
          },
          "404": {
            "description": "Commentaire non trouvé",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Commentaire non trouvé",
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Une erreur est survenue lors de la MAJ du commentaire",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Une erreur est survenue lors de la MAJ du commentaire",
                  "type": "string"
                }
              }
            }
          }
        },
        "description": "Modification d'un commentaire",
        "operationId": "PUT_api-movies-idMovie-comments-idComment",
        "requestBody": {
          "content": {
            "application/json": {
              "example": {
                "_id": "XXXXXX",
                "name": "Test 2",
                "email": "test@test.new",
                "movie_id": "573a1390f29313caabcd42e8",
                "text": "Test Text",
                "date": "2024-03-24T19:45:45.920Z"
              },
              "schema": {
                "type": "object"
              }
            }
          },
          "required": true
        }
      },
      "delete": {
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "acknowledged": true,
                    "deletedCount": 1
                  },
                  "type": "object"
                }
              }
            }
          },
          "404": {
            "description": "Commentaire non trouvé",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Commentaire non trouvé",
                  "type": "string"
                }
              }
            }
          },
          "500": {
            "description": "Une erreur est survenue lors de la suppression du commentaire",
            "content": {
              "application/json": {
                "schema": {
                  "example": "Une erreur est survenue lors de la suppression du commentaire",
                  "type": "string"
                }
              }
            }
          }
        },
        "description": "Suppression d'un commentaire",
        "operationId": "DELETE_api-movies-idMovie-comments-idComment"
      },
      "parameters": [
        {
          "name": "idComment",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string"
          }
        },
        {
          "name": "idMovie",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ]
    }
  },
  "components": {
    "schemas": {},
    "responses": {},
    "parameters": {},
    "examples": {},
    "requestBodies": {},
    "headers": {},
    "securitySchemes": {},
    "links": {},
    "callbacks": {}
  }
}